server.port=8080

elasticsearch.host=elasticsearch
elasticsearch.port=9200
elasticsearch.username=your_username
elasticsearch.password=your_password

productIndex.filePath=./termIndex.txt
completionIndex.filePath=./completionIndex.txt