# Elasticsearch ????
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.username=your_username
elasticsearch.password=your_password
test=99
#????,???sources?????termIndex.txt??
productIndex.filePath=/Users/wesen/Desktop/suggest/src/main/resources/termIndex.txt
completionIndex.filePath=/Users/wesen/Desktop/suggest/src/main/resources/completionIndex.txt